services:
  backend:
    build: .
    container_name: docflow_backend

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      STORAGE_PATH: ${STORAGE_PATH}

    volumes:
      - files_storage:${STORAGE_PATH}

volumes:
  files_storage: