spring.application.name=DocFlowBackend

server.port=8080
ip.service=192.168.0.6

docflow.upload.path=/home/empresa/docflow/documents/uploads
docflow.win.path=C:/docflow/documents/uploads

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.datasource.url=jdbc:mysql://localhost:3306/doc_flow
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
